let TankProcedure = {
  'FREE': 'FREE',
  'FETCHING_UPLOAD_TOKEN': 'FETCHING_UPLOAD_TOKEN',
  'UPLOADING': 'UPLOADING',
  'FETCHING_DOWNLOAD_TOKEN': 'FETCHING_DOWNLOAD_TOKEN',
  'DOWNLOADING': 'DOWNLOADING'
}

export {TankProcedure}
